flutter_application_path = '../../flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'ios_module_test' do
  install_all_flutter_pods(flutter_application_path)
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        flutter_additional_ios_build_settings(target)
        target.build_configurations.each do |config|
            # Workaround for https://github.com/flutter/flutter/issues/64502
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES' # <= this line
        end
    end
  flutter_post_install(installer) if defined?(flutter_post_install)
end